#!/usr/bin/env bash
# setup-local-env.sh
#
# Generates azure-ai/functions/.env from:
#   - Terraform Cloud state   (search endpoint, search key, resource group)
#   - Azure Container App secrets  (inference endpoint, inference key)
#
# Prerequisites:
#   terraform  — logged into Terraform Cloud  (terraform login)
#   az         — logged into Azure CLI        (az login)
#   python3    — available in PATH

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="$SCRIPT_DIR/../terraform"
ENV_FILE="$SCRIPT_DIR/../functions/.env"

# ── Prerequisite checks ───────────────────────────────────────────────────────
for cmd in terraform az python3; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is required but not found in PATH." >&2
    exit 1
  fi
done

# ── Pull Terraform outputs ────────────────────────────────────────────────────
echo "Fetching Terraform outputs from Terraform Cloud..."
TF_OUT=$(cd "$TF_DIR" && terraform output -json)

SEARCH_SERVICE=$(echo "$TF_OUT" | python3 -c \
  "import json,sys; print(json.load(sys.stdin)['search_service_name']['value'])")
AZURE_SEARCH_ENDPOINT="https://${SEARCH_SERVICE}.search.windows.net"

AZURE_SEARCH_KEY=$(echo "$TF_OUT" | python3 -c \
  "import json,sys; print(json.load(sys.stdin)['search_admin_key']['value'])")

RESOURCE_GROUP=$(echo "$TF_OUT" | python3 -c \
  "import json,sys; print(json.load(sys.stdin)['resource_group_name']['value'])")

# ── Pull Container App secrets from Azure ─────────────────────────────────────
echo "Fetching inference secrets from Azure Container App..."
APP_NAME="resumeai-app"

AZURE_INFERENCE_ENDPOINT=$(az containerapp secret show \
  --name "$APP_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --secret-name inference-endpoint \
  --query value \
  --output tsv)

AZURE_INFERENCE_KEY=$(az containerapp secret show \
  --name "$APP_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --secret-name inference-key \
  --query value \
  --output tsv)

# ── Write .env ────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-local-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT — this file is listed in .gitignore

AZURE_SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
AZURE_SEARCH_KEY=${AZURE_SEARCH_KEY}
AZURE_SEARCH_INDEX_NAME=resume-content

AZURE_INFERENCE_ENDPOINT=${AZURE_INFERENCE_ENDPOINT}
AZURE_INFERENCE_KEY=${AZURE_INFERENCE_KEY}

# localhost origins for local testing only — never add these to Terraform ALLOWED_ORIGINS
ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
EOF

chmod 600 "$ENV_FILE"
echo "Done — written to $ENV_FILE (permissions: 600)"
echo ""
echo "To start the API locally:"
echo "  cd azure-ai/functions"
echo "  pip install -r requirements.txt"
echo "  set -a && source .env && set +a"
echo "  uvicorn function_app:app --reload --port 8001"
