name: CI-dev

on:
  push:
    branches: [ dev ]
  pull_request:

  workflow_dispatch:

env:
  DEFAULT_DOC: resume.html

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Link Checking
        id: linkcheck
        uses: peter-evans/link-checker@v1.2.2
        with:
          args: -v -r *
          
      - name: Report Missing Links
        if: ${{ steps.linkcheck.outputs.exit_code != 0 }}
        run: |
          echo "::warning::Broken links have been detected"
          #echo "::error::Broken links have been detected"
          #exit ${{ steps.linkcheck.outputs.exit_code }}