name: CI-dev

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

env:
  DEFAULT_DOC: resume.html
  IS_DEPLOY: ${{ github.ref == 'refs/heads/dev' && github.event_name == 'push' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Link Checking
        id: linkcheck
        uses: peter-evans/link-checker@v1.2.2
        with:
          args: -v -r *
          
      - name: Report Missing Links
        if: ${{ steps.linkcheck.outputs.exit_code != 0 }}
        run: |
          echo "::warning::Broken links have been detected"
          #echo "::error::Broken links have been detected"
          #exit ${{ steps.linkcheck.outputs.exit_code }}

      - name: Generate PDF
        uses: fifsky/html-to-pdf-action@v0.0.2
        with:
          htmlFile: ./src/${{ env.DEFAULT_DOC }}
          outputFile: ./src/Todd_DeBlieck_Resume-dev.pdf
          pdfOptions: '{"printBackground": true, "preferCSSPageSize": true, "format": "Tabloid", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      
      - name: Minify
        if: ${{ env.IS_DEPLOY == 'true' }}
        uses: Charlesworth/compress-action@1.0.0
        with:
          target-directory: ./src