name: CI

on:
  push:
    branches: [ main ]
  pull_request:

    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Link Checking
        id: linkcheck
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.html'
          fail: false

      - name: Report Missing Links
        if: ${{ steps.linkcheck.outputs.exit_code != 0 }}
        run: echo "::warning::Broken links have been detected"

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML (for PDF)
        run: pandoc ./src/Todd_DeBlieck_Resume.md -f gfm -t html -o ./src/Todd_DeBlieck_Resume.print.html

      - name: Generate PDF
        uses: fifsky/html-to-pdf-action@v0.0.2
        with:
          htmlFile: ./src/Todd_DeBlieck_Resume.print.html
          outputFile: ./src/Todd_DeBlieck_Resume.pdf
          pdfOptions: '{"printBackground": true, "preferCSSPageSize": true, "format": "Tabloid", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      
      - name: Minify
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: Charlesworth/compress-action@1.0.0
        with:
          target-directory: ./src

      - name: Create index.html for GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: cp ./src/resume.html ./src/index.html
      
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          cname: todd.deblieck.me
