name: CI

on:
  push:
    branches: [ main ]
  pull_request:

    
  workflow_dispatch:

env:
  DEFAULT_DOC: resume.html
  AWS_REGION: us-east-1
  IS_DEPLOY: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Link Checking
        id: linkcheck
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.html'
          fail: false

      - name: Report Missing Links
        if: ${{ steps.linkcheck.outputs.exit_code != 0 }}
        run: echo "::warning::Broken links have been detected"

      - name: Generate PDF
        uses: fifsky/html-to-pdf-action@v0.0.2
        with:
          htmlFile: ./src/${{ env.DEFAULT_DOC }}
          outputFile: ./src/Todd_DeBlieck_Resume.pdf
          pdfOptions: '{"printBackground": true, "preferCSSPageSize": true, "format": "Tabloid", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      
      - name: Minify
        if: ${{ env.IS_DEPLOY == 'true' }}
        uses: Charlesworth/compress-action@1.0.0
        with:
          target-directory: ./src
      
      - name: Configure AWS Credentials
        if: ${{ env.IS_DEPLOY == 'true' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        if: ${{ env.IS_DEPLOY == 'true' }}
        run: aws s3 sync ./src s3://${{ secrets.AWS_S3_BUCKET }} --follow-symlinks --delete
