name: cleanup-wf

on:
  workflow_dispatch:

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
