name: cleanup-wf

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: styfle/cancel-workflow-action@0.12.0
      with:
        access_token: ${{ github.token }}
