name: Lint

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: HTML Linting
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DISABLE_ERRORS: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}