name: Markdown-HTML

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Markdown-HTML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Markdown-HTML
        uses: ZacJW/markdown-html-action@1.1.1
        with:
          input_files: ./src/resume.html